name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.2'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Set up Git user
      run: |
        git config --global user.name "Sajesh Bahing"
        git config --global user.email "sajesh.bahing22@gmail.com"

    - name: Create gh-pages branch if doesn't exist
      run: |
        git checkout --orphan gh-pages
        git rm -rf .
        git commit --allow-empty -m "Initial gh-pages commit"
        git push origin gh-pages
        git checkout main
      continue-on-error: true

    - name: Deploy
      run: npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Enable this once tests are added
    # - name: Test
    #   run: npm run test -- --watchAll=false